server:
  port: 8082
  servlet:
    context-path: /api
spring:
  application:
    name: ms-history
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: ms_history
      port: 27017
      host: localhost